apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  completions: 5 # insgesamt fuenf Pods starten
  parallelism: 2 # immer zwei parallel
  template:
    spec:
      containers:
      - name: busybox-job-container
        image: busybox:1.34
        args: # alternativ: command: ["/bin/sh", "-c", "date; echo Hallo Busybox"]
        - /bin/sh
        - -c
        - date; echo Hallo Busybox
      restartPolicy: OnFailure # alternativ: Never (nur einmal starten)
  backoffLimit: 4 # max. 4x neu starten
