apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ...
  namespace: ...
subjects: # More than one subject is allowed
- kind: User # User, Group or ServiceAccount
  name: ...
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # Role or ClusterRole
  name: ... # Matches the name of the (Cluster)Role; see pod-role.yaml
  apiGroup: rbac.authorization.k8s.io
