apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ...
  namespace: ...
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core ApiGroup, * for all apiGroups
  resources: ["pods"] # * for all resources
  verbs: ["get", "list", "watch", "update"] # * for all verbs
