apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PVC-NAME # Verwendung in pv.yaml
  labels:
    app: ...
spec:
  accessModes:
    - ReadWriteOnce # siehe https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  resources:
    requests:
      storage: ... # Beispiel 1GB: 1Gi
